export const USERS = [
  {
    id: "u1",
    username: "alex",
    password: "alex123",
    name: "Alexandra Chen",
    role: "CEO",
    initials: "AC",
    color: "#6366f1",
  },
  {
    id: "u2",
    username: "rajesh",
    password: "raj123",
    name: "Rajesh Kumar",
    role: "CFO",
    initials: "RK",
    color: "#8b5cf6",
  },
  {
    id: "u3",
    username: "sarah",
    password: "sar123",
    name: "Sarah Mitchell",
    role: "COO",
    initials: "SM",
    color: "#ec4899",
  },
  {
    id: "u4",
    username: "david",
    password: "dav123",
    name: "David Park",
    role: "CTO",
    initials: "DP",
    color: "#14b8a6",
  },
  {
    id: "u5",
    username: "priya",
    password: "pri123",
    name: "Priya Sharma",
    role: "Legal Director",
    initials: "PS",
    color: "#f59e0b",
  },
];
